spring:
  datasource:
    url: jdbc:h2:file:./data/marathon
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT:8080}

external:
  api:
    key: ${EXTERNAL_API_KEY:c64e32404715c51e584ef0d9217b07b8f564de06bbbf10118da7a012f4dd2371}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
